### ISSUE TITLE
error TS2507: Type 'typeof FilterBase' is not a constructor function type.

### ISSUE THREAD

**Issue by hoghweed** [ravendb/ravendb-nodejs-client#311] opened 2022-06-06 14:59 UTC
I'm using ravendb within my pnpm monorepo. 
When I try to build my project using typescript, I have a sad error reporting:

```bash
error TS2507: Type 'typeof FilterBase' is not a constructor function type.

 6 export declare class TransformKeysJsonStream extends FilterBase {

Found 1 error in ../../node_modules/.pnpm/ravendb@5.2.3/node_modules/ravendb/dist/Mapping/Json/Streams/TransformKeysJsonStream.d.ts:6
```

My configuration is:
- A pnpm monorepo
- Typescript project ver 4.7.2
- Node 16.12.0

I installed all the types for:
- `bluebird`
- `readable-stream`
- `stream-json`
- `ws`

I solved all the problems installing the types but for the above is quite impossible to solve it.
Any idea?

Thanks in advance

**Comment by ml054** [comment] 2022-06-07 09:03
Hi, 

All deps like `readable-stream`, `stream-json` should be installed along with ravendb automatically and there is no need to install them manually. Could you share some project template which demonstrate your issue? Looks like pnpm resolves deps in different way then npm (maybe due unflat?)

**Comment by Kloen** [comment] 2022-06-15 12:21
@ml054 not sure if it's the same case, but I just faced almost the same issue, this is, likely, a bare minimum case able to reproduce the issue:

https://github.com/Kloen/ravendb-ts-error/runs/6899500064

**Comment by ml054** [comment] 2022-06-17 07:07
@Kloen I reproduced your issue. Working on the fix. Thanks :)

**Comment by ml054** [comment] 2022-06-17 09:23
@Kloen  @hoghweed  You can track progress here: https://issues.hibernatingrhinos.com/issue/RDBC-592

**Comment by ml054** [comment] 2022-06-17 10:01
Fixed in https://github.com/ravendb/ravendb-nodejs-client/pull/313

**Closed as completed by ml054** 2022-06-17 10:01 UTC

**Comment by ml054** [comment] 2022-06-17 10:03
I'd about to release version 5.2.4.

**Comment by ml054** [comment] 2022-06-17 10:40
5.2.4 released  - verified your example - it compiles successfully

**Comment by Kloen** [comment] 2022-06-17 11:09
Thank you!
